In [2]:
for i in ['l','a','x']:
    if i == 'a':
        break

In [18]:
#Function - A block of code - which runs when it is called 
#A function defenition - I have defined what this function should do.
A = 100
def sample_function():
    print("Hello from inside a function - I run whenever called")
    print(A)

In [21]:
A

100

In [19]:
sample_function()

Hello from inside a function - I run whenever called
100


In [22]:
def sample_function(A):
    print("Hello from inside a function - I run whenever called")
    print(A)
    return A

In [23]:
sample_function()

TypeError: sample_function() missing 1 required positional argument: 'A'

In [13]:
A = 100
A = sample_function(A)

Hello from inside a function - I run whenever called
100


In [6]:
print(A)

500


In [4]:
#function call 
sample_function()

Hello from inside a function - I run whenever called


In [5]:
sample_function()

Hello from inside a function - I run whenever called


In [6]:
sample_function()

Hello from inside a function - I run whenever called


In [7]:
sample_function()

Hello from inside a function - I run whenever called


In [8]:
sample_function()

Hello from inside a function - I run whenever called


In [9]:
sample_function()

Hello from inside a function - I run whenever called


In [10]:
#() - Arguments into function, Arguments are information provided to a functiuon
def student_salut(stu_name):
    print("Hello {}, welcome to incepetez learning....".format(stu_name))

In [11]:
student_salut('siju')

Hello siju, welcome to incepetez learning....


In [19]:
student_salut('ashok')

Hello ashok, welcome to incepetez learning....


In [14]:
a = ['ashok','anandh']
for i in a: 
    student_salut(i)

Hello ashok, welcome to incepetez learning....
Hello anandh, welcome to incepetez learning....


In [27]:
#() - Arguments into function, Arguments are information provided to a functiuon
def student_score(stu_name,stu_name2,stu_name3):
    print("Hello {1}, {2} welcome to {0} incepetez learning....".format(stu_name,stu_name2,stu_name3))

In [28]:
student_score('ashok','ram','Mani')

Hello ram, Mani welcome to ashok incepetez learning....


In [34]:
#function with default parameter - Function with default parameter 
def inceptez_batch(batch=20):
    batch_ = str(batch)
    print("hello people from batch {}".format(batch_))
    next_batch = batch+1
    print("the next batch slot is availabl for batch: {}".format(next_batch))

In [35]:
inceptez_batch()

hello people from batch 20
the next batch slot is availabl for batch: 21


In [ ]:
#Write a function that takes in two variables a&b and prints the sum of a+b - run the for consequtive numbers from 1-10

the numbers are 1, 2 
sum of the numbers: 3 
the numbers are 2, 3 
sum of the numbers: 5

In [50]:
def sum_(a,b):
    print("the numbers are {},{}".format(a,b))
    print("sum of the numbers: ",a+b)
for i in range(1,10):
    result = sum_(i,i+1)

the numbers are 1,2
sum of the numbers:  3
the numbers are 2,3
sum of the numbers:  5
the numbers are 3,4
sum of the numbers:  7
the numbers are 4,5
sum of the numbers:  9
the numbers are 5,6
sum of the numbers:  11
the numbers are 6,7
sum of the numbers:  13
the numbers are 7,8
sum of the numbers:  15
the numbers are 8,9
sum of the numbers:  17
the numbers are 9,10
sum of the numbers:  19


In [45]:
sum_("Muthu",'kumaran')

the numbers are Muthu,kumaran
sum of the numbers:  Muthukumaran


In [97]:
def sum_(a,b):
    print("the numbers are {},{}".format(a,b))
    print("sum of the numbers: ",a+100)
sum_("Muthu",'kumaran')

the numbers are Muthu,kumaran


TypeError: can only concatenate str (not "int") to str

In [98]:
def sum_(a,b):
    """
    a- integer (range - 0-100)
    b- integer (range - 100-200)
    """
    print("the numbers are {},{}".format(a,b))
    print("sum of the numbers: ",a+b)
    return a+b

In [99]:
sum_?

In [43]:
for i in range(1,10):
    result = sum_(i,i+1)
    print("The returned value ",result*100)
    print("The returned value ",result**2)

the numbers are 1,2
sum of the numbers:  3
The returned value  300
The returned value  9
the numbers are 2,3
sum of the numbers:  5
The returned value  500
The returned value  25
the numbers are 3,4
sum of the numbers:  7
The returned value  700
The returned value  49
the numbers are 4,5
sum of the numbers:  9
The returned value  900
The returned value  81
the numbers are 5,6
sum of the numbers:  11
The returned value  1100
The returned value  121
the numbers are 6,7
sum of the numbers:  13
The returned value  1300
The returned value  169
the numbers are 7,8
sum of the numbers:  15
The returned value  1500
The returned value  225
the numbers are 8,9
sum of the numbers:  17
The returned value  1700
The returned value  289
the numbers are 9,10
sum of the numbers:  19
The returned value  1900
The returned value  361


In [42]:
result

19

In [ ]:
sum_(a,b)

In [52]:
import numpy

In [54]:
import numpy as np

In [55]:
arr = np.array([1,2,58])

In [56]:
print(type(arr))

<class 'numpy.ndarray'>


In [57]:
arr.shape

(3,)

In [ ]:
arr

In [114]:
array_2d = np.array([[1,2,3],[5,6,7]])

In [115]:
array_2d.shape

(2, 3)

In [61]:
array_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [69]:
array_3d = np.array([[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]]])

In [70]:
array_3d.shape

(3, 2, 3)

In [68]:
array_3d

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [80]:
#Function involved in creating an array 
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = a.reshape((4,4))

In [82]:
a

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [78]:
a = a.reshape((1,4,4))

In [79]:
a.shape

(1, 4, 4)

In [77]:
a = a.reshape((3,3))

ValueError: cannot reshape array of size 16 into shape (3,3)

In [83]:
#transpose of a matrix - Tranforming my rows to columns and columns to rows 
a.T 

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [89]:
#linspace: the function generates elements (array) with are euqally spaced..
#Start - Stop - Number of elements 
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [96]:
np.linspace?
#help(np.linspace)
#print(np.linspace.__doc__)

In [87]:
#arange 
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [86]:
np.arange?

In [101]:
from sum_me import _sum_

In [103]:
_sum_?

In [104]:
from sum_me import *

In [105]:
from Preprocessing.sum_example import *

In [106]:
mul_(1,2)

2

In [108]:
#zero 
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [109]:
#ones 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
#eye 
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
#Iterating through an array 
arr

array([ 1,  2, 58])

In [136]:
arr.reshape((3,1))

array([[ 1],
       [ 2],
       [58]])

In [112]:
for i in arr:
    print(i)

1
2
58


In [128]:
array_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [132]:
for i in array_2d:
    print(i)
    for j in i: 
        print(j)

[1 2 3]
1
2
3
[5 6 7]
5
6
7


In [133]:
type(arr[0])

numpy.int64

In [137]:
array_3d

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [144]:
for i in array_3d:
    print('Inside Sheets')
    print(i)
    for j in i: 
        print("inside Matrix")
        print(j)
        for k in j: 
            print(k)

Inside Sheets
[[1 2 3]
 [5 6 7]]
inside Matrix
[1 2 3]
1
2
3
inside Matrix
[5 6 7]
5
6
7
Inside Sheets
[[1 2 3]
 [5 6 7]]
inside Matrix
[1 2 3]
1
2
3
inside Matrix
[5 6 7]
5
6
7
Inside Sheets
[[1 2 3]
 [5 6 7]]
inside Matrix
[1 2 3]
1
2
3
inside Matrix
[5 6 7]
5
6
7


In [146]:
import json 

str_ = '{"key1":"value1","key2":"value2"}'

In [151]:
i_p = json.loads(str_)

In [152]:
for key in json.loads(str_):
    print(i_p[key])

value1
value2


In [153]:
json.dumps?

In [155]:
#Addition 
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [156]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [159]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [160]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [161]:

arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [162]:
np.add(arr1,arr2)

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [ ]:
subtraction & multiplication - What is the issue with np.multiply & np.dot

In [163]:
arr1-arr2

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [164]:
np.subtract(arr1, arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [171]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [172]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [165]:
np.multiply(arr1, arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [168]:
np.dot(arr1, arr2)

array([[ 900, 1000, 1100, 1200],
       [2020, 2280, 2540, 2800],
       [3140, 3560, 3980, 4400],
       [4260, 4840, 5420, 6000]])

In [169]:
np.dot?

In [170]:
np.divide(arr1, arr2)

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [173]:
arr1*10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [ ]:
#joining two arrays 

In [174]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

In [175]:
np.stack((arr1,arr2),axis = 0) #stacking along rows

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [176]:
np.stack((arr1,arr2),axis = 1) #stacking along columns

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [177]:
np.stack((arr1,arr2),axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [178]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [188]:
np.concatenate?

In [180]:
np.concatenate((arr1, arr2),axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [181]:
np.concatenate?

In [185]:
a = np.array([[1,0],[0,1]])
b = np.array([[4,1],[2,2]])

In [186]:
np.matmul(a,b) #dot product

array([[4, 1],
       [2, 2]])

In [187]:
a @ b #dot

array([[4, 1],
       [2, 2]])

In [ ]:
[[1,2,3,5,6],
[4,5,6,7,8]]

In [189]:
#sort an array 
arr_2d = np.array([[1,2,3],[20,9,2]])

In [190]:
arr_2d

array([[ 1,  2,  3],
       [20,  9,  2]])

In [191]:
np.sort?

In [192]:
np.sort(arr_2d)

array([[ 1,  2,  3],
       [ 2,  9, 20]])

In [196]:
#searching in the array
arr = np.array([6,7,8,9,10,11,12,50,44])

In [197]:
np.where(arr > 8)

(array([3, 4, 5, 6, 7, 8]),)

In [200]:
np.where?

In [ ]:
#statistics 

In [206]:
arr = np.array([6,7,8,9,10,12,50,44])
np.mean(arr)

18.25

In [202]:
np.mean?

In [207]:
np.median(arr)

9.5

In [208]:
np.std(arr)

16.753730927766508

In [209]:
np.random?

In [211]:
np.random.randint(1,100,size=(2,2))

array([[85, 83],
       [63, 96]])

In [212]:
np.nan

nan

In [8]:
A

100